[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"   # good for firebase-admin

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
