[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"   # good for firebase-admin

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  # netlify.toml

# Long-cache static assets produced by Next
[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Everything else is dynamic: don't cache
[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate"

